"""add eligibility rules

Revision ID: 247ee5a6930b
Revises: 765309797aed
Create Date: 2026-09-06 12:47:39.067331
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "247ee5a6930b"
down_revision: str | None = "765309797aed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eligibility_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("call_document_id", sa.UUID(), nullable=False),
        sa.Column("criterion", sa.String(length=100), nullable=False),
        sa.Column("operator", sa.String(length=50), nullable=False),
        sa.Column("expected_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_hard", sa.Boolean(), nullable=False),
        sa.Column(
            "extraction_status",
            sa.Enum("supported", "unsupported", name="eligibility_extraction_status"),
            nullable=False,
        ),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=500), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("human_confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["call_document_id"], ["call_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eligibility_rules")
    # ### end Alembic commands ###
