"""add document evidence chunks

Revision ID: 30871e895922
Revises: adc5b6a299e3
Create Date: 2026-09-06 15:15:38.871261
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "30871e895922"
down_revision: str | None = "adc5b6a299e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("call_document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=500), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_checksum", sa.String(length=64), nullable=False),
        sa.CheckConstraint("chunk_index >= 0", name="ck_call_document_chunks_index"),
        sa.CheckConstraint("page IS NULL OR page >= 1", name="ck_call_document_chunks_page"),
        sa.CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset",
            name="ck_call_document_chunks_offsets",
        ),
        sa.ForeignKeyConstraint(["call_document_id"], ["call_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "call_document_id", "chunk_index", name="uq_call_document_chunks_document_index"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("call_document_chunks")
    # ### end Alembic commands ###
