"""add euroscivoc taxonomy

Revision ID: 765309797aed
Revises: afcd135157a1
Create Date: 2026-09-06 12:19:50.865893
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "765309797aed"
down_revision: str | None = "afcd135157a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "euroscivoc_concepts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("uri", sa.String(length=2048), nullable=False),
        sa.Column("notation", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column("deprecated", sa.Boolean(), nullable=False),
        sa.Column("preferred_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("alternative_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["snapshot_id"], ["dataset_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "uri", name="uq_euroscivoc_concept_snapshot"),
    )
    op.create_table(
        "euroscivoc_broader_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.UUID(), nullable=False),
        sa.Column("broader_concept_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["broader_concept_id"], ["euroscivoc_concepts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["concept_id"], ["euroscivoc_concepts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("concept_id", "broader_concept_id", name="uq_euroscivoc_broader"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("euroscivoc_broader_relations")
    op.drop_table("euroscivoc_concepts")
    # ### end Alembic commands ###
