"""Expand funding call metadata.

Revision ID: adc5b6a299e3
Revises: bc87ae5493ff
Create Date: 2026-09-06 15:09:09.633255
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "adc5b6a299e3"
down_revision: str | None = "bc87ae5493ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("funding_calls", sa.Column("topic_id", sa.String(length=255), nullable=True))
    for column_name in (
        "scope",
        "expected_outcomes",
        "expected_impact",
        "applicant_conditions",
        "consortium_conditions",
    ):
        op.add_column(
            "funding_calls",
            sa.Column(column_name, sa.Text(), server_default="", nullable=False),
        )
    op.add_column("funding_calls", sa.Column("action_type", sa.String(length=100), nullable=True))
    op.add_column(
        "funding_calls",
        sa.Column("funding_rate", sa.Numeric(precision=5, scale=4), nullable=True),
    )
    op.add_column("funding_calls", sa.Column("trl_min", sa.Integer(), nullable=True))
    op.add_column("funding_calls", sa.Column("trl_max", sa.Integer(), nullable=True))
    op.add_column(
        "funding_calls",
        sa.Column(
            "adapter_version",
            sa.String(length=100),
            server_default="legacy-unrecorded",
            nullable=False,
        ),
    )
    op.add_column(
        "funding_calls", sa.Column("snapshot_checksum", sa.String(length=64), nullable=True)
    )
    op.execute(sa.text("UPDATE funding_calls SET topic_id = source_call_id"))
    for column_name in (
        "scope",
        "expected_outcomes",
        "expected_impact",
        "applicant_conditions",
        "consortium_conditions",
        "adapter_version",
    ):
        op.alter_column("funding_calls", column_name, server_default=None)
    op.create_check_constraint(
        "ck_funding_calls_funding_rate",
        "funding_calls",
        "funding_rate IS NULL OR (funding_rate >= 0 AND funding_rate <= 1)",
    )
    op.create_check_constraint(
        "ck_funding_calls_trl_min",
        "funding_calls",
        "trl_min IS NULL OR (trl_min >= 1 AND trl_min <= 9)",
    )
    op.create_check_constraint(
        "ck_funding_calls_trl_max",
        "funding_calls",
        "trl_max IS NULL OR (trl_max >= 1 AND trl_max <= 9)",
    )
    op.create_check_constraint(
        "ck_funding_calls_trl_range",
        "funding_calls",
        "trl_min IS NULL OR trl_max IS NULL OR trl_min <= trl_max",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for constraint_name in (
        "ck_funding_calls_trl_range",
        "ck_funding_calls_trl_max",
        "ck_funding_calls_trl_min",
        "ck_funding_calls_funding_rate",
    ):
        op.drop_constraint(constraint_name, "funding_calls", type_="check")
    op.drop_column("funding_calls", "snapshot_checksum")
    op.drop_column("funding_calls", "adapter_version")
    op.drop_column("funding_calls", "trl_max")
    op.drop_column("funding_calls", "trl_min")
    op.drop_column("funding_calls", "consortium_conditions")
    op.drop_column("funding_calls", "applicant_conditions")
    op.drop_column("funding_calls", "funding_rate")
    op.drop_column("funding_calls", "action_type")
    op.drop_column("funding_calls", "expected_impact")
    op.drop_column("funding_calls", "expected_outcomes")
    op.drop_column("funding_calls", "scope")
    op.drop_column("funding_calls", "topic_id")
    # ### end Alembic commands ###
