"""Add CORDIS historical data

Revision ID: afcd135157a1
Revises: c3f9d7fe6113
Create Date: 2026-09-06 12:01:15.040583
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "afcd135157a1"
down_revision: str | None = "c3f9d7fe6113"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_path", sa.String(length=2048), nullable=False),
        sa.Column("row_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "checksum", name="uq_dataset_snapshot_source_hash"),
    )
    op.create_table(
        "historical_projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("source_project_id", sa.String(length=100), nullable=False),
        sa.Column("acronym", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=2000), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("framework_programme", sa.String(length=255), nullable=False),
        sa.Column("funding_scheme", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("eu_contribution", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.ForeignKeyConstraint(["snapshot_id"], ["dataset_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id", "source_project_id", name="uq_historical_project_snapshot"
        ),
    )
    op.create_table(
        "historical_project_euroscivoc",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=255), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["historical_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "code", name="uq_project_euroscivoc"),
    )
    op.create_table(
        "historical_project_topics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["historical_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "topic_id", name="uq_project_topic"),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("source_organisation_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=1000), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=True),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("sme", sa.Boolean(), nullable=True),
        sa.Column("eu_contribution", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["historical_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "source_organisation_id", "role", name="uq_participant_role"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("participants")
    op.drop_table("historical_project_topics")
    op.drop_table("historical_project_euroscivoc")
    op.drop_table("historical_projects")
    op.drop_table("dataset_snapshots")
    # ### end Alembic commands ###
