"""add historical project search index

Revision ID: bc87ae5493ff
Revises: 247ee5a6930b
Create Date: 2026-09-06 13:46:18.460200
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "bc87ae5493ff"
down_revision: str | None = "247ee5a6930b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_projects",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(objective, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_historical_projects_search_vector",
        "historical_projects",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_historical_projects_search_vector",
        table_name="historical_projects",
        postgresql_using="gin",
    )
    op.drop_column("historical_projects", "search_vector")
    # ### end Alembic commands ###
