"""Track source document checksums

Revision ID: c3f9d7fe6113
Revises: d5eee4d546cd
Create Date: 2026-09-06 11:52:37.651929
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c3f9d7fe6113"
down_revision: str | None = "d5eee4d546cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "call_documents", sa.Column("source_checksum", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("call_documents", "source_checksum")
    # ### end Alembic commands ###
