"""Add call documents

Revision ID: d5eee4d546cd
Revises: 20260905_01
Create Date: 2026-09-06 11:48:01.621081
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d5eee4d546cd"
down_revision: str | None = "20260905_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("funding_call_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=1000), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("checksum_verified", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["funding_call_id"], ["funding_calls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("funding_call_id", "checksum", name="uq_call_documents_call_checksum"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("call_documents")
    # ### end Alembic commands ###
